//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Airport_Management_System1
{
    using System;
    using System.Collections.Generic;
    
    public partial class flight
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public flight()
        {
            this.Resrvaations = new HashSet<Resrvaation>();
        }
    
        public int id { get; set; }
        public double time { get; set; }
        public System.DateTime ArriveDate { get; set; }
        public System.DateTime DepartureDate { get; set; }
        public double Distance { get; set; }
        public int Capacity { get; set; }
        public Nullable<int> FromCity { get; set; }
        public Nullable<int> ToCity { get; set; }
        public Nullable<int> AirPlainId { get; set; }
    
        public virtual AirPlain AirPlain { get; set; }
        public virtual City City { get; set; }
        public virtual City City1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Resrvaation> Resrvaations { get; set; }
    }
}
