//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Airport_Management_System1
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AirplainDBEntities : DbContext
    {
        public AirplainDBEntities()
            : base("name=AirplainDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AirPlain> AirPlains { get; set; }
        public virtual DbSet<City> Cities { get; set; }
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<flight> flights { get; set; }
        public virtual DbSet<Resrvaation> Resrvaations { get; set; }
        public virtual DbSet<Tickt> Tickts { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
